using AgileAI.Abstractions;
using AgileAI.Core;
using AgileAI.Extensions.FileSystem;
using AgileAI.Studio.Api.Contracts;
using AgileAI.Studio.Api.Domain;
using System.Text.Json;

namespace AgileAI.Studio.Api.Services;

public class AgentExecutionService(
    ConversationService conversationService,
    AgentService agentService,
    ModelCatalogService modelCatalogService,
    ProviderClientFactory providerClientFactory,
    FileSystemToolRegistryFactory toolRegistryFactory)
{
    private const int AutoGeneratedTitleMessageCount = 2;
    private static readonly JsonSerializerOptions SseJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public async Task<ChatResultDto> SendMessageAsync(Guid conversationId, string content, CancellationToken cancellationToken)
    {
        var conversation = await conversationService.GetConversationEntityAsync(conversationId, cancellationToken);
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var trimmedContent = content.Trim();

        var userMessage = await conversationService.AddMessageAsync(conversation.Id, MessageRole.User, trimmedContent, false, null, null, null, cancellationToken);

        var session = CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient);
        var response = await session.SendAsync(trimmedContent, new ChatOptions
        {
            Temperature = agent.Temperature,
            MaxTokens = agent.MaxTokens
        }, cancellationToken);

        if (!response.IsSuccess)
        {
            throw new InvalidOperationException(response.ErrorMessage ?? "Model request failed.");
        }

        var assistantText = response.Message?.TextContent ?? string.Empty;
        var assistant = await conversationService.AddMessageAsync(
            conversation.Id,
            MessageRole.Assistant,
            assistantText,
            false,
            response.FinishReason,
            response.Usage?.PromptTokens,
            response.Usage?.CompletionTokens,
            cancellationToken);

        await TryGenerateConversationTitleAsync(conversation, trimmedContent, assistantText, cancellationToken);
        await conversationService.TouchConversationAsync(conversation, cancellationToken);

        return new ChatResultDto(
            ConversationService.MapConversation(conversation),
            ConversationService.MapMessage(userMessage),
            ConversationService.MapMessage(assistant));
    }

    public async Task StreamMessageAsync(Guid conversationId, string content, HttpResponse response, CancellationToken cancellationToken)
    {
        var conversation = await conversationService.GetConversationEntityAsync(conversationId, cancellationToken);
        var trimmedContent = content.Trim();
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var toolRegistry = toolRegistryFactory.CreateDefaultRegistry();
        var requestMessages = BuildRequestHistory(conversation, agent).Append(ChatMessage.User(trimmedContent)).ToList();
        var requestOptions = new ChatOptions
        {
            Temperature = agent.Temperature,
            MaxTokens = agent.MaxTokens,
            Tools = toolRegistry.GetToolDefinitions()
        };
        var userMessage = await conversationService.AddMessageAsync(conversation.Id, MessageRole.User, trimmedContent, false, null, null, null, cancellationToken);
        var assistant = await conversationService.AddMessageAsync(conversation.Id, MessageRole.Assistant, string.Empty, true, null, null, null, cancellationToken);

        response.Headers.ContentType = "text/event-stream";
        response.Headers.CacheControl = "no-cache";

        await WriteSseAsync(response, "message-created", new
        {
            userMessage = ConversationService.MapMessage(userMessage),
            assistantMessage = ConversationService.MapMessage(assistant),
            conversation = ConversationService.MapConversation(conversation)
        }, cancellationToken);

        try
        {
            var assistantContent = string.Empty;
            string? finishReason = null;
            int? inputTokens = null;
            int? outputTokens = null;

            await foreach (var update in chatClient.StreamAsync(new ChatRequest
            {
                ModelId = runtime.RuntimeModelId,
                Messages = requestMessages,
                Options = requestOptions
            }, cancellationToken))
            {
                switch (update)
                {
                    case TextDeltaUpdate textDelta:
                        assistantContent += textDelta.Delta;
                        await WriteSseAsync(response, "text-delta", new { delta = textDelta.Delta }, cancellationToken);
                        break;
                    case UsageUpdate usageUpdate:
                        inputTokens = usageUpdate.Usage.PromptTokens;
                        outputTokens = usageUpdate.Usage.CompletionTokens;
                        await WriteSseAsync(response, "usage", new
                        {
                            inputTokens,
                            outputTokens
                        }, cancellationToken);
                        break;
                    case CompletedUpdate completedUpdate:
                        finishReason = completedUpdate.FinishReason;
                        break;
                    case ErrorUpdate errorUpdate:
                        throw new InvalidOperationException(errorUpdate.ErrorMessage);
                }
            }

            await conversationService.UpdateMessageAsync(
                assistant,
                assistantContent,
                false,
                finishReason,
                inputTokens,
                outputTokens,
                cancellationToken);
            await TryGenerateConversationTitleAsync(conversation, trimmedContent, assistantContent, cancellationToken);
            await WriteSseAsync(response, "final-message", new
            {
                content = assistantContent,
                finishReason,
                inputTokens,
                outputTokens
            }, cancellationToken);
            await WriteSseAsync(response, "completed", new { finishReason }, cancellationToken);
            await conversationService.TouchConversationAsync(conversation, cancellationToken);
        }
        catch (Exception ex)
        {
            await conversationService.UpdateMessageAsync(assistant, ex.Message, false, null, null, null, cancellationToken);
            await WriteSseAsync(response, "error", new { message = ex.Message }, cancellationToken);
        }
    }

    private async Task<ExecutionResult> SendMessageWithSessionAsync(Conversation conversation, string content, CancellationToken cancellationToken)
    {
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var session = CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient);

        var response = await session.SendAsync(content, new ChatOptions
        {
            Temperature = agent.Temperature,
            MaxTokens = agent.MaxTokens
        }, cancellationToken);

        if (!response.IsSuccess)
        {
            throw new InvalidOperationException(response.ErrorMessage ?? "Model request failed.");
        }

        return new ExecutionResult(
            response.Message?.TextContent ?? string.Empty,
            response.FinishReason,
            response.Usage?.PromptTokens,
            response.Usage?.CompletionTokens);
    }

    private ChatSession CreateSession(Conversation conversation, AgentDefinition agent, string runtimeModelId, IChatClient chatClient)
    {
        var selectedToolNames = agentService.GetSelectedToolNamesAsync(agent.Id, CancellationToken.None).GetAwaiter().GetResult();
        var toolRegistry = toolRegistryFactory.CreateRegistry(selectedToolNames);
        var history = BuildRequestHistory(conversation, agent);

        return new ChatSessionBuilder(chatClient, runtimeModelId)
            .WithToolRegistry(toolRegistry)
            .WithHistory(history)
            .Build();
    }

    private static string BuildSystemPrompt(string basePrompt)
        => string.Join(
            Environment.NewLine + Environment.NewLine,
            new[]
            {
                basePrompt.Trim(),
                "You have access to workspace tools inside the AgileAI repository.",
                "Use list_directory or search_files before guessing file paths, use read_file or read_files_batch to inspect text files, and use write_file only when creating or updating workspace files is necessary.",
                "Never claim to have read or written a file unless you actually used the tool."
            }.Where(x => string.IsNullOrWhiteSpace(x) == false));

    private async Task TryGenerateConversationTitleAsync(Conversation conversation, string userContent, string assistantContent, CancellationToken cancellationToken)
    {
        if (conversation.Messages.Count > AutoGeneratedTitleMessageCount ||
            string.IsNullOrWhiteSpace(userContent) ||
            string.IsNullOrWhiteSpace(assistantContent) ||
            IsAutoGeneratedTitle(conversation.Title, conversation.AgentDefinition?.Name) == false)
        {
            return;
        }

        var fallbackTitle = BuildFallbackConversationTitle(userContent);

        try
        {
            var title = await GenerateConversationTitleAsync(conversation, userContent, assistantContent, cancellationToken);
            await conversationService.RenameConversationAsync(conversation, string.IsNullOrWhiteSpace(title) ? fallbackTitle : title, cancellationToken);
        }
        catch
        {
            await conversationService.RenameConversationAsync(conversation, fallbackTitle, cancellationToken);
        }
    }

    private async Task<string?> GenerateConversationTitleAsync(Conversation conversation, string userContent, string assistantContent, CancellationToken cancellationToken)
    {
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);

        var response = await chatClient.CompleteAsync(new ChatRequest
        {
            ModelId = runtime.RuntimeModelId,
            Messages =
            [
                ChatMessage.System("You create concise chat session titles. Respond with only a short title in plain text, under 8 words, no quotes, no markdown, and match the user's language when possible."),
                ChatMessage.User($"Create a session title for this conversation.\n\nUser: {userContent}\n\nAssistant: {assistantContent}")
            ],
            Options = new ChatOptions
            {
                Temperature = 0.2,
                MaxTokens = 24
            }
        }, cancellationToken);

        if (!response.IsSuccess)
        {
            return null;
        }

        return response.Message?.TextContent?
            .Replace("\"", string.Empty, StringComparison.Ordinal)
            .Replace("#", string.Empty, StringComparison.Ordinal)
            .Trim();
    }

    private static bool IsAutoGeneratedTitle(string title, string? agentName)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return true;
        }

        if (string.IsNullOrWhiteSpace(agentName))
        {
            return false;
        }

        return string.Equals(title.Trim(), $"{agentName} session", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), $"{agentName} chat", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), "New chat", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), "New Session", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildFallbackConversationTitle(string userContent)
    {
        var singleLine = string.Join(' ', userContent
            .Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Trim();

        if (singleLine.Length == 0)
        {
            return "New Session";
        }

        var title = singleLine.Length > 48 ? singleLine[..48].Trim() : singleLine;
        return title.TrimEnd('.', '。', ',', '，', ':', '：', ';', '；', '!', '！', '?', '？');
    }

    private static IReadOnlyList<ChatMessage> BuildRequestHistory(Conversation conversation, AgentDefinition agent)
    {
        var history = new List<ChatMessage>
        {
            ChatMessage.System(BuildSystemPrompt(agent.SystemPrompt))
        };

        foreach (var message in conversation.Messages.OrderBy(x => x.CreatedAtUtc))
        {
            switch (message.Role)
            {
                case MessageRole.System:
                    history.Add(ChatMessage.System(message.Content));
                    break;
                case MessageRole.User:
                    history.Add(ChatMessage.User(message.Content));
                    break;
                case MessageRole.Assistant:
                    history.Add(ChatMessage.Assistant(message.Content));
                    break;
                case MessageRole.Tool:
                    history.Add(new ChatMessage
                    {
                        Role = ChatRole.Tool,
                        ToolCallId = message.Id.ToString(),
                        TextContent = message.Content
                    });
                    break;
            }
        }

        return history;
    }

    private sealed record ExecutionResult(string AssistantContent, string? FinishReason, int? InputTokens, int? OutputTokens);

    private static async Task WriteSseAsync(HttpResponse response, string eventName, object payload, CancellationToken cancellationToken)
    {
        var json = JsonSerializer.Serialize(payload, SseJsonOptions);
        await response.WriteAsync($"event: {eventName}\n", cancellationToken);
        await response.WriteAsync($"data: {json}\n\n", cancellationToken);
        await response.Body.FlushAsync(cancellationToken);
    }
}
