using AgileAI.Abstractions;
using AgileAI.Core;
using AgileAI.Extensions.FileSystem;
using AgileAI.Studio.Api.Contracts;
using AgileAI.Studio.Api.Domain;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AgileAI.Studio.Api.Services;

public class AgentExecutionService(
    ConversationService conversationService,
    AgentService agentService,
    ModelCatalogService modelCatalogService,
    ProviderClientFactory providerClientFactory,
    IServiceProvider serviceProvider,
    IAgentRuntime agentRuntime,
    ISkillRegistry skillRegistry,
    ISessionStore sessionStore,
    ISkillPlanner skillPlanner,
    ISkillContinuationPolicy skillContinuationPolicy,
    StudioToolRegistryFactory toolRegistryFactory,
    StudioToolExecutionGate toolExecutionGate,
    ToolApprovalService toolApprovalService)
{
    private const int AutoGeneratedTitleMessageCount = 2;
    private const int StudioMaxToolLoopIterations = 12;
    private static readonly JsonSerializerOptions SseJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    public async Task<ChatResultDto> SendMessageAsync(Guid conversationId, string content, CancellationToken cancellationToken)
    {
        var conversation = await conversationService.GetConversationEntityAsync(conversationId, cancellationToken);
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var trimmedContent = content.Trim();

        var userMessage = await conversationService.AddMessageAsync(conversation.Id, MessageRole.User, trimmedContent, false, null, null, null, null, null, cancellationToken);

        async Task<ChatResultDto> ExecuteStudioChatSessionFallbackAsync()
        {
            var session = CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient);
            var turn = await session.SendTurnAsync(trimmedContent, new ChatOptions
            {
                Temperature = agent.Temperature,
                MaxTokens = agent.MaxTokens
            }, cancellationToken);

            var response = turn.Response;

            if (!response.IsSuccess)
            {
                throw new InvalidOperationException(response.ErrorMessage ?? "Model request failed.");
            }

            var assistantText = turn.PendingApprovalRequest == null
                ? response.Message?.TextContent ?? string.Empty
                : $"Command approval required for {turn.PendingApprovalRequest.ToolName}.";
            var assistant = await conversationService.AddMessageAsync(
                conversation.Id,
                MessageRole.Assistant,
                assistantText,
                false,
                response.FinishReason,
                response.Usage?.PromptTokens,
                response.Usage?.CompletionTokens,
                null,
                GetAppliedToolNames(response.Message?.ToolCalls, turn.ToolResults),
                cancellationToken);

            if (turn.PendingApprovalRequest != null)
            {
                await toolApprovalService.CreatePendingApprovalAsync(
                    conversation,
                    assistant.Id,
                    turn.PendingApprovalRequest,
                    response.Message?.TextContent ?? string.Empty,
                    cancellationToken);
            }

            await TryGenerateConversationTitleAsync(conversation, trimmedContent, assistantText, cancellationToken);
            await conversationService.TouchConversationAsync(conversation, cancellationToken);

            return new ChatResultDto(
                await conversationService.MapConversationAsync(conversation, cancellationToken),
                ConversationService.MapMessage(userMessage),
                ConversationService.MapMessage(assistant));
        }

        if (agent.EnableSkills)
        {
            var allowedSkillNames = await agentService.GetAllowedSkillNamesAsync(agent.Id, cancellationToken);
            var runtimeResult = await agentRuntime.ExecuteAsync(new AgentRequest
            {
                SessionId = conversation.Id.ToString(),
                ModelId = runtime.RuntimeModelId,
                Input = trimmedContent,
                EnableSkills = true,
                AllowedSkills = allowedSkillNames,
                Metadata = new Dictionary<string, object?>
                {
                    ["conversationId"] = conversation.Id.ToString(),
                    ["agentId"] = agent.Id.ToString(),
                    ["studioModelId"] = agent.StudioModelId.ToString()
                }
            }, cancellationToken);

            if (!runtimeResult.IsSuccess)
            {
                if ((runtimeResult.ErrorMessage ?? string.Empty).Contains("Provider '", StringComparison.OrdinalIgnoreCase))
                {
                    return await ExecuteStudioChatSessionFallbackAsync();
                }

                throw new InvalidOperationException(runtimeResult.ErrorMessage ?? "Skill runtime request failed.");
            }

            var runtimeAssistantText = runtimeResult.Output ?? string.Empty;
            var assistantMessage = await conversationService.AddMessageAsync(
                conversation.Id,
                MessageRole.Assistant,
                runtimeAssistantText,
                false,
                null,
                null,
                null,
                null,
                null,
                cancellationToken);

            await TryGenerateConversationTitleAsync(conversation, trimmedContent, runtimeAssistantText, cancellationToken);
            await conversationService.TouchConversationAsync(conversation, cancellationToken);

            return new ChatResultDto(
                await conversationService.MapConversationAsync(conversation, cancellationToken),
                ConversationService.MapMessage(userMessage),
                ConversationService.MapMessage(assistantMessage));
        }

        return await ExecuteStudioChatSessionFallbackAsync();
    }

    public async Task StreamMessageAsync(Guid conversationId, string content, HttpResponse response, CancellationToken cancellationToken)
    {
        var conversation = await conversationService.GetConversationEntityAsync(conversationId, cancellationToken);
        var trimmedContent = content.Trim();
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var userMessage = await conversationService.AddMessageAsync(conversation.Id, MessageRole.User, trimmedContent, false, null, null, null, null, null, cancellationToken);
        var assistant = await conversationService.AddMessageAsync(conversation.Id, MessageRole.Assistant, string.Empty, true, null, null, null, null, null, cancellationToken);

        response.Headers.ContentType = "text/event-stream";
        response.Headers.CacheControl = "no-cache";

        await WriteSseAsync(response, "message-created", new
        {
            userMessage = ConversationService.MapMessage(userMessage),
            assistantMessage = ConversationService.MapMessage(assistant),
            conversation = await conversationService.MapConversationAsync(conversation, cancellationToken)
        }, cancellationToken);

        try
        {
            if (agent.EnableSkills)
            {
                var selectedToolNames = await agentService.GetSelectedToolNamesAsync(agent.Id, cancellationToken);
                var allowedSkillNames = await agentService.GetAllowedSkillNamesAsync(agent.Id, cancellationToken);
                var agentRequest = new AgentRequest
                {
                    SessionId = conversation.Id.ToString(),
                    ModelId = runtime.RuntimeModelId,
                    Input = trimmedContent,
                    EnableSkills = true,
                    AllowedSkills = allowedSkillNames,
                    Metadata = new Dictionary<string, object?>
                    {
                        ["conversationId"] = conversation.Id.ToString(),
                        ["agentId"] = agent.Id.ToString(),
                        ["studioModelId"] = agent.StudioModelId.ToString()
                    }
                };

                var resolvedSkill = await ResolveSkillForStreamingAsync(agentRequest, conversation.Id, cancellationToken);
                if (resolvedSkill != null)
                {
                    var preparedHistory = SkillPromptHelper.PrepareHistoryForSkill(
                        BuildRequestHistory(conversation, agent).ToList(),
                        resolvedSkill.Manifest!).ToList();

                    if (selectedToolNames.Count == 0)
                    {
                        await StreamPlainChatAsync(preparedHistory, runtime.RuntimeModelId, chatClient, assistant, response, conversation, trimmedContent, cancellationToken, resolvedSkill.Name);
                        return;
                    }

                    var skillSession = CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient, preparedHistory);
                    await StreamSessionTurnAsync(
                        skillSession,
                        trimmedContent,
                        conversation,
                        assistant,
                        response,
                        cancellationToken,
                        resolvedSkill.Name,
                        agentRequest.Metadata);
                    return;
                }
            }

            await StreamSessionTurnAsync(
                CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient),
                trimmedContent,
                conversation,
                assistant,
                response,
                cancellationToken,
                null,
                new Dictionary<string, object?>
                {
                    ["conversationId"] = conversation.Id.ToString(),
                    ["agentId"] = agent.Id.ToString(),
                    ["studioModelId"] = agent.StudioModelId.ToString()
                });
        }
        catch (Exception ex)
        {
            await conversationService.UpdateMessageAsync(assistant, ex.Message, false, null, null, null, null, null, cancellationToken);
            await WriteSseAsync(response, "error", new { message = ex.Message }, cancellationToken);
        }
    }

    private async Task<ISkill?> ResolveSkillForStreamingAsync(AgentRequest request, Guid conversationId, CancellationToken cancellationToken)
    {
        var sessionState = await sessionStore.GetAsync(conversationId.ToString(), cancellationToken);
        var skills = skillRegistry.GetAllSkills() ?? [];
        if (skills.Count == 0)
        {
            return null;
        }

        if (!string.IsNullOrWhiteSpace(request.PreferredSkill))
        {
            var preferred = skills.FirstOrDefault(x => string.Equals(x.Name, request.PreferredSkill, StringComparison.OrdinalIgnoreCase));
            if (preferred != null && (request.AllowedSkills == null || request.AllowedSkills.Contains(preferred.Name, StringComparer.OrdinalIgnoreCase)))
            {
                return preferred;
            }
        }

        var continuationDecision = await skillContinuationPolicy.DecideAsync(request, sessionState, skills, cancellationToken);
        if (continuationDecision.ContinueActiveSkill && !string.IsNullOrWhiteSpace(continuationDecision.SkillName))
        {
            var continuedSkill = skills.FirstOrDefault(x => string.Equals(x.Name, continuationDecision.SkillName, StringComparison.OrdinalIgnoreCase));
            if (continuedSkill != null && (request.AllowedSkills == null || request.AllowedSkills.Contains(continuedSkill.Name, StringComparer.OrdinalIgnoreCase)))
            {
                return continuedSkill;
            }
        }

        var skillPlan = await skillPlanner.PlanAsync(request, skills, cancellationToken);
        if (!skillPlan.ShouldUseSkill || string.IsNullOrWhiteSpace(skillPlan.SkillName))
        {
            return null;
        }

        return skills.FirstOrDefault(x => string.Equals(x.Name, skillPlan.SkillName, StringComparison.OrdinalIgnoreCase));
    }

    private async Task StreamPlainChatAsync(
        IReadOnlyList<ChatMessage> messages,
        string modelId,
        IChatClient chatClient,
        ConversationMessage assistant,
        HttpResponse response,
        Conversation conversation,
        string userContent,
        CancellationToken cancellationToken,
        string? activeSkill = null)
    {
        var assistantBuilder = new StringBuilder();
        string? finishReason = null;
        int? inputTokens = null;
        int? outputTokens = null;

        await foreach (var update in chatClient.StreamAsync(new ChatRequest
        {
            ModelId = modelId,
            Messages = messages,
            Options = new ChatOptions
            {
                Temperature = conversation.AgentDefinition?.Temperature,
                MaxTokens = conversation.AgentDefinition?.MaxTokens
            }
        }, cancellationToken))
        {
            switch (update)
            {
                case TextDeltaUpdate textDelta:
                    assistantBuilder.Append(textDelta.Delta);
                    await WriteSseAsync(response, "text-delta", new { delta = textDelta.Delta }, cancellationToken);
                    break;
                case UsageUpdate usageUpdate:
                    inputTokens = usageUpdate.Usage.PromptTokens;
                    outputTokens = usageUpdate.Usage.CompletionTokens;
                    await WriteSseAsync(response, "usage", new { inputTokens, outputTokens }, cancellationToken);
                    break;
                case CompletedUpdate completedUpdate:
                    finishReason = completedUpdate.FinishReason;
                    break;
                case ErrorUpdate errorUpdate:
                    throw new InvalidOperationException(errorUpdate.ErrorMessage);
            }
        }

        var assistantContent = assistantBuilder.ToString();
        await conversationService.UpdateMessageAsync(
            assistant,
            assistantContent,
            false,
            finishReason,
            inputTokens,
            outputTokens,
            activeSkill,
            null,
            cancellationToken);

        if (!string.IsNullOrWhiteSpace(activeSkill))
        {
            await sessionStore.SaveAsync(new ConversationState
            {
                SessionId = conversation.Id.ToString(),
                History = messages.Concat([ChatMessage.Assistant(assistantContent)]).ToList(),
                ActiveSkill = activeSkill,
                Metadata = new Dictionary<string, object?>
                {
                    ["conversationId"] = conversation.Id.ToString(),
                    ["agentId"] = conversation.AgentDefinitionId.ToString(),
                    ["studioModelId"] = conversation.AgentDefinition?.StudioModelId.ToString()
                },
                UpdatedAt = DateTimeOffset.UtcNow
            }, cancellationToken);
        }
        else
        {
            await sessionStore.SaveAsync(new ConversationState
            {
                SessionId = conversation.Id.ToString(),
                History = messages.Concat([ChatMessage.Assistant(assistantContent)]).ToList(),
                ActiveSkill = null,
                Metadata = new Dictionary<string, object?>
                {
                    ["conversationId"] = conversation.Id.ToString(),
                    ["agentId"] = conversation.AgentDefinitionId.ToString(),
                    ["studioModelId"] = conversation.AgentDefinition?.StudioModelId.ToString()
                },
                UpdatedAt = DateTimeOffset.UtcNow
            }, cancellationToken);
        }

        await TryGenerateConversationTitleAsync(conversation, userContent, assistantContent, cancellationToken);
        await WriteSseAsync(response, "final-message", new
        {
            content = assistantContent,
            finishReason,
            inputTokens,
            outputTokens,
            appliedSkillName = activeSkill,
            appliedToolNames = (string[]?)null
        }, cancellationToken);
        await WriteSseAsync(response, "completed", new { finishReason }, cancellationToken);
        await conversationService.TouchConversationAsync(conversation, cancellationToken);
    }

    private async Task StreamSessionTurnAsync(
        IChatSession session,
        string userContent,
        Conversation conversation,
        ConversationMessage assistant,
        HttpResponse response,
        CancellationToken cancellationToken,
        string? activeSkill,
        IReadOnlyDictionary<string, object?>? metadata)
    {
        await foreach (var update in session.StreamTurnAsync(userContent, new ChatOptions
        {
            Temperature = conversation.AgentDefinition?.Temperature,
            MaxTokens = conversation.AgentDefinition?.MaxTokens
        }, cancellationToken))
        {
            switch (update)
            {
                case ChatTurnTextDelta textDelta:
                    await WriteSseAsync(response, "text-delta", new { delta = textDelta.Delta }, cancellationToken);
                    break;
                case ChatTurnUsage usage:
                    await WriteSseAsync(response, "usage", new
                    {
                        inputTokens = usage.Usage.PromptTokens,
                        outputTokens = usage.Usage.CompletionTokens
                    }, cancellationToken);
                    break;
                case ChatTurnPendingApproval pendingApproval:
                    await PersistConversationStateAsync(conversation, session.History, activeSkill, metadata, cancellationToken);

                    var waitingContent = $"Command approval required for {pendingApproval.PendingApprovalRequest.ToolName}.";
                    await conversationService.UpdateMessageAsync(assistant, waitingContent, false, null, null, null, activeSkill, pendingApproval.ToolNames, cancellationToken);

                    var approval = await toolApprovalService.CreatePendingApprovalAsync(
                        conversation,
                        assistant.Id,
                        pendingApproval.PendingApprovalRequest,
                        pendingApproval.Response.Message?.TextContent ?? string.Empty,
                        cancellationToken);

                    await WriteSseAsync(response, "approval-required", approval, cancellationToken);
                    await WriteSseAsync(response, "final-message", new
                    {
                        content = waitingContent,
                        finishReason = (string?)null,
                        inputTokens = (int?)null,
                        outputTokens = (int?)null,
                        appliedSkillName = activeSkill,
                        appliedToolNames = pendingApproval.ToolNames
                    }, cancellationToken);
                    await WriteSseAsync(response, "completed", new { finishReason = "approval_required" }, cancellationToken);
                    await conversationService.TouchConversationAsync(conversation, cancellationToken);
                    return;
                case ChatTurnCompleted completed:
                    if (!completed.Response.IsSuccess)
                    {
                        throw new InvalidOperationException(completed.Response.ErrorMessage ?? "Model request failed.");
                    }

                    var assistantContent = completed.Response.Message?.TextContent ?? string.Empty;
                    await conversationService.UpdateMessageAsync(
                        assistant,
                        assistantContent,
                        false,
                        completed.Response.FinishReason,
                        completed.Response.Usage?.PromptTokens,
                        completed.Response.Usage?.CompletionTokens,
                        activeSkill,
                        completed.ToolNames,
                        cancellationToken);
                    await PersistConversationStateAsync(conversation, session.History, activeSkill, metadata, cancellationToken);
                    await TryGenerateConversationTitleAsync(conversation, userContent, assistantContent, cancellationToken);
                    await WriteSseAsync(response, "final-message", new
                    {
                        content = assistantContent,
                        finishReason = completed.Response.FinishReason,
                        inputTokens = completed.Response.Usage?.PromptTokens,
                        outputTokens = completed.Response.Usage?.CompletionTokens,
                        appliedSkillName = activeSkill,
                        appliedToolNames = completed.ToolNames
                    }, cancellationToken);
                    await WriteSseAsync(response, "completed", new { finishReason = completed.Response.FinishReason }, cancellationToken);
                    await conversationService.TouchConversationAsync(conversation, cancellationToken);
                    return;
                case ChatTurnError error:
                    throw new InvalidOperationException(error.ErrorMessage);
            }
        }

        throw new InvalidOperationException("Streaming turn ended without a terminal update.");
    }

    private async Task PersistConversationStateAsync(
        Conversation conversation,
        IReadOnlyList<ChatMessage> history,
        string? activeSkill,
        IReadOnlyDictionary<string, object?>? metadata,
        CancellationToken cancellationToken)
    {
        await sessionStore.SaveAsync(new ConversationState
        {
            SessionId = conversation.Id.ToString(),
            History = history,
            ActiveSkill = activeSkill,
            Metadata = metadata?.ToDictionary(static entry => entry.Key, static entry => entry.Value)
                ?? new Dictionary<string, object?>
                {
                    ["conversationId"] = conversation.Id.ToString(),
                    ["agentId"] = conversation.AgentDefinitionId.ToString(),
                    ["studioModelId"] = conversation.AgentDefinition?.StudioModelId.ToString()
                },
            UpdatedAt = DateTimeOffset.UtcNow
        }, cancellationToken);
    }

    private static IReadOnlyList<string>? GetAppliedToolNames(IReadOnlyList<ToolCall>? toolCalls, IReadOnlyList<ToolResult>? toolResults)
    {
        if (toolCalls == null || toolCalls.Count == 0)
        {
            return null;
        }

        var executedToolCallIds = toolResults?
            .Select(result => result.ToolCallId)
            .Where(toolCallId => string.IsNullOrWhiteSpace(toolCallId) == false)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return toolCalls
            .Where(toolCall => executedToolCallIds == null || executedToolCallIds.Count == 0 || executedToolCallIds.Contains(toolCall.Id))
            .Select(toolCall => toolCall.Name)
            .Where(name => string.IsNullOrWhiteSpace(name) == false)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private async Task<ExecutionResult> SendMessageWithSessionAsync(Conversation conversation, string content, CancellationToken cancellationToken)
    {
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);
        var session = CreateSession(conversation, agent, runtime.RuntimeModelId, chatClient);

        var response = await session.SendAsync(content, new ChatOptions
        {
            Temperature = agent.Temperature,
            MaxTokens = agent.MaxTokens
        }, cancellationToken);

        if (!response.IsSuccess)
        {
            throw new InvalidOperationException(response.ErrorMessage ?? "Model request failed.");
        }

        return new ExecutionResult(
            response.Message?.TextContent ?? string.Empty,
            response.FinishReason,
            response.Usage?.PromptTokens,
            response.Usage?.CompletionTokens);
    }

    private ChatSession CreateSession(Conversation conversation, AgentDefinition agent, string runtimeModelId, IChatClient chatClient, IReadOnlyList<ChatMessage>? historyOverride = null)
    {
        var selectedToolNames = agentService.GetSelectedToolNamesAsync(agent.Id, CancellationToken.None).GetAwaiter().GetResult();
        var toolRegistry = toolRegistryFactory.CreateRegistry(selectedToolNames);
        var history = historyOverride ?? BuildRequestHistory(conversation, agent);

        return new ChatSessionBuilder(chatClient, runtimeModelId)
            .WithToolRegistry(toolRegistry)
            .WithMaxToolLoopIterations(StudioMaxToolLoopIterations)
            .WithToolExecutionGate(toolExecutionGate)
            .UseServiceProvider(serviceProvider)
            .WithConversationId(conversation.Id.ToString())
            .WithHistory(history)
            .Build();
    }

    public static string BuildSystemPrompt(string basePrompt)
        => string.Join(
            Environment.NewLine + Environment.NewLine,
            new[]
            {
                basePrompt.Trim(),
                "You have access to workspace tools inside the AgileAI repository.",
                "Use list_directory or search_files before guessing file paths, use read_file or read_files_batch to inspect text files, and use write_file only when creating or updating workspace files is necessary.",
                "Never claim to have read or written a file unless you actually used the tool."
            }.Where(x => string.IsNullOrWhiteSpace(x) == false));

    private async Task TryGenerateConversationTitleAsync(Conversation conversation, string userContent, string assistantContent, CancellationToken cancellationToken)
    {
        if (conversation.Messages.Count > AutoGeneratedTitleMessageCount ||
            string.IsNullOrWhiteSpace(userContent) ||
            string.IsNullOrWhiteSpace(assistantContent) ||
            IsAutoGeneratedTitle(conversation.Title, conversation.AgentDefinition?.Name) == false)
        {
            return;
        }

        var fallbackTitle = BuildFallbackConversationTitle(userContent);

        try
        {
            var title = await GenerateConversationTitleAsync(conversation, userContent, assistantContent, cancellationToken);
            await conversationService.RenameConversationAsync(conversation, string.IsNullOrWhiteSpace(title) ? fallbackTitle : title, cancellationToken);
        }
        catch
        {
            await conversationService.RenameConversationAsync(conversation, fallbackTitle, cancellationToken);
        }
    }

    private async Task<string?> GenerateConversationTitleAsync(Conversation conversation, string userContent, string assistantContent, CancellationToken cancellationToken)
    {
        var agent = conversation.AgentDefinition ?? throw new InvalidOperationException("Conversation agent is missing.");
        var runtime = await modelCatalogService.GetRuntimeOptionsAsync(agent.StudioModelId, cancellationToken);
        var chatClient = providerClientFactory.CreateClient(runtime);

        var response = await chatClient.CompleteAsync(new ChatRequest
        {
            ModelId = runtime.RuntimeModelId,
            Messages =
            [
                ChatMessage.System("You create concise chat session titles. Respond with only a short title in plain text, under 8 words, no quotes, no markdown, and match the user's language when possible."),
                ChatMessage.User($"Create a session title for this conversation.\n\nUser: {userContent}\n\nAssistant: {assistantContent}")
            ],
            Options = new ChatOptions
            {
                Temperature = 0.2,
                MaxTokens = 24
            }
        }, cancellationToken);

        if (!response.IsSuccess)
        {
            return null;
        }

        return response.Message?.TextContent?
            .Replace("\"", string.Empty, StringComparison.Ordinal)
            .Replace("#", string.Empty, StringComparison.Ordinal)
            .Trim();
    }

    private static bool IsAutoGeneratedTitle(string title, string? agentName)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return true;
        }

        if (string.IsNullOrWhiteSpace(agentName))
        {
            return false;
        }

        return string.Equals(title.Trim(), $"{agentName} session", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), $"{agentName} chat", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), "New chat", StringComparison.OrdinalIgnoreCase)
            || string.Equals(title.Trim(), "New Session", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildFallbackConversationTitle(string userContent)
    {
        var singleLine = string.Join(' ', userContent
            .Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Trim();

        if (singleLine.Length == 0)
        {
            return "New Session";
        }

        var title = singleLine.Length > 48 ? singleLine[..48].Trim() : singleLine;
        return title.TrimEnd('.', '。', ',', '，', ':', '：', ';', '；', '!', '！', '?', '？');
    }

    private static IReadOnlyList<ChatMessage> BuildRequestHistory(Conversation conversation, AgentDefinition agent)
    {
        var history = new List<ChatMessage>
        {
            ChatMessage.System(BuildSystemPrompt(agent.SystemPrompt))
        };

        foreach (var message in conversation.Messages.OrderBy(x => x.CreatedAtUtc))
        {
            switch (message.Role)
            {
                case MessageRole.System:
                    history.Add(ChatMessage.System(message.Content));
                    break;
                case MessageRole.User:
                    history.Add(ChatMessage.User(message.Content));
                    break;
                case MessageRole.Assistant:
                    history.Add(ChatMessage.Assistant(message.Content));
                    break;
                case MessageRole.Tool:
                    history.Add(new ChatMessage
                    {
                        Role = ChatRole.Tool,
                        ToolCallId = message.Id.ToString(),
                        TextContent = message.Content
                    });
                    break;
            }
        }

        return history;
    }

    private sealed record ExecutionResult(string AssistantContent, string? FinishReason, int? InputTokens, int? OutputTokens);

    private static async Task WriteSseAsync(HttpResponse response, string eventName, object payload, CancellationToken cancellationToken)
    {
        var json = JsonSerializer.Serialize(payload, SseJsonOptions);
        await response.WriteAsync($"event: {eventName}\n", cancellationToken);
        await response.WriteAsync($"data: {json}\n\n", cancellationToken);
        await response.Body.FlushAsync(cancellationToken);
    }
}
